[package]
name = "zip-pesel-cracker"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = { version = "0.4", default-features = false}
clap = { version = "4", features = [ "derive" ] }
zip = "2.4.2"
